server.port=9712
server.address=0.0.0.0
endpoint.address=127.0.0.1:9200

caches.expiry.timeout=3600

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.maximum-pool-size=2
spring.datasource.connection-timeout=60000
spring.datasource.leak-detection-threshold=60000
spring.datasource.minimum-idle=2

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.lock-retry-count=10
spring.flyway.enabled=true

# JWT
security.jwt.secret=ea782f11b7fc70d1ec70a83ea78dcd9b157981ce2c844b183db728534b62db45
security.jwt.expiration=3600000
# not used, for later experiment
jwt.whitelistUrl=/auth/login|/auth/register|/auth/ping